Permit passing config object via env vars
radiantearth/stac-browser pull request #461
Opened 2024-08-07 22:00 UTC by alukach

If a config value is an object, the tooling to convert it from an environment var to JS will keep it as a string (see #460).

This PR will instead retain its state as a JSON object.

This will allow the following configurations to be correctly set via environment variables:

```sh
▶ cat config.schema.json | jq '.properties | to_entries | map(select(.value.type[0] == "object")) | map(.key)'
[
  "requestHeaders",
  "requestQueryParameters",
  "authConfig"
]
```

closes #460

2024-08-09 16:35 UTC, m-mohr requested changes
Thank you for the suggestion.
Indeed, it is not supported to pass objects via ENV or CLI and it is reflected as such in the docs and config.schema.js.
If this works reliably, this should be reflected in the docs and in the config.schema.js.

2024-08-09 17:46 UTC, alukach commented
@m-mohr Ah, I had missed those details. Thanks for pointing out that this is documented and intended behavior.  In [408ed94](https://github.com/radiantearth/stac-browser/pull/461/commits/408ed94024fbf7b31ab11460b2f0be016bbbb5a8) and [88212c8](https://github.com/radiantearth/stac-browser/pull/461/commits/88212c862046a23a6054bb115f2ee28620fb6997) I've removed such documentation in hopes that we can indeed adjust this beavior.

2024-08-09 17:53 UTC, alukach commented
(Seeing that this PR is not a trivial one-liner as I had initially hoped, I've updated the description in hopes of adding more clarity to what is being changed and why)

2025-01-09 12:48 UTC, m-mohr commented
Hi @alukach 

I checked this again, but I'm not sure how this allows supporting objects. I only see changes in the Docker environment, but not generally in the non-Docker part of STAC Browser. As such I'm not sure how this is meant to work?! Can you provide an example, please?

2025-01-09 14:18 UTC, alukach commented
@m-mohr you're correct, I was generally unaware of how configuration was parsed in a non-dockerized environment and that was not addressed. It is not addressed via [b738e4e](https://github.com/radiantearth/stac-browser/pull/461/commits/b738e4ee944dada08210739726d5bd43031a89d2). Do you require a more substantial demonstration of its functionality?

2025-01-09 16:48 UTC, m-mohr commented
Thanks. This looks reasonable, but I don't see any effect.

For example, `npm run build -- --requestHeaders="{"x-example": "abc"}"` doesn't seem to have any effect. How did you confirm that the changes work? What example did you test it with?

2025-01-09 20:39 UTC, alukach commented
@m-mohr For testing, I've been using `npm start`:

```
npm start -- --open --catalogUrl "https://earth-search.aws.element84.com/v1/" --authConfig '{ "type": "openIdConnect", "openIdConnectUrl": "https://cognito-idp.us-east-1.amazonaws.com/abcd123/.well-known/openid-configuration", "oidcOptions": { "client_id": "stac-browser" } }'
```

<img width="484" alt="image" src="https://github.com/user-attachments/assets/f0fd5114-dfbd-4107-a658-881d9217f4ac" />

> For example, `npm run build -- --requestHeaders="{"x-example": "abc"}"` doesn't seem to have any effect.

Not sure if this is the exact reason for your issues, but you should wrap the JSON in single quotes rather than double quotes.

2025-01-09 20:53 UTC, alukach commented
@m-mohr I've removed [bd68d93](https://github.com/radiantearth/stac-browser/pull/461/commits/bd68d93b4cb16ee5c960cacc74e74ee08d2f3099) from this PR as I have been unable to replicate this issue. 

With the following command:

```
npm start -- --open --catalogUrl "https://earth-search.aws.element84.com/v1/" --requestHeaders='{"X-Amzn-Trace-Id": "example"}'  
```

I can see that the trace ID is correctly set on all outgoing requests (I use that header to conform with the `access-control-allow-headers` response returned by the server on OPTIONS requests).

<img width="858" alt="image" src="https://github.com/user-attachments/assets/ff2314b5-f439-4ce9-b80d-d715f16bc05d" />

2025-01-09 21:46 UTC, m-mohr commented
Something must be off on my machine, I can't provide anything via CLI right now. Might be a Windows thing or something is broken in a specific npm/node/vue-cli version. Need to investigate. Can't really test this otherwise. But good to know that this is working for you.

bd68d93 came from the master branch.

2025-01-09 23:02 UTC, m-mohr commented
Okay, I can confirm that this works. It is an npm bug on Windows that prevented me from testing this.

2025-01-09 23:03 UTC, m-mohr approved these changes

2025-01-09 23:03 UTC, merged