Docs docker details
radiantearth/stac-browser pull request #512
Opened 2024-12-08 18:02 UTC by alekzvik

Add a docs section to describe how the docker image works.

Interest was expressed here: #511

2024-12-08 18:03 UTC, alekzvik commented
@m-mohr since you first expressed interest in this doc, please take a look and let me know what is missing and what can be improved

2024-12-09 11:18 UTC, m-mohr requested changes
Thanks, I appreciate it. I left a couple of editorial suggestions.

Generally, I think we could move the whole Docker section from the README to the docker.md and just leave the header and a link to the docs in the README. That would slim down the README a bit. But just an idea, not a must.

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +Note: Docker might not be an ideal way to deploy stac browser in production. Consider using cloud storage and CDN.
```suggestion
Note: Docker might not be an ideal way to deploy STAC Browser in production. Consider using a web host, cloud storage, or a CDN. 
```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +# How it works
```suggestion
## How it works

```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +# Essential parts
```suggestion
## Essential parts

```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +So, essentialy, in the end you get an nginx instance that serves static files.
```suggestion
The docker image uses a multi stage build.
The first stage is based on a node image and runs `npm build` to produce a `/dist` folder with static files (HTML, CSS, and JavaScript).
The second stage is based on a nginx image that serves the folder with static files and deals with the build-only options such as `pathPrefix`.
So, essentialy, in the end you get an nginx instance that serves the static files.
```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +3. /docker/docker-entrypoint.sh - a start script to read the passed variables and produce `config.js` file.
```suggestion
1. [Dockerfile](../Dockerfile) - contains information on how to build the image.
2. [docker/default.conf](../docker/default.conf) - nginx configuration template, where `<pathPrefix>` is replaced during build.
3. [docker/docker-entrypoint.sh](../docker/docker-entrypoint.sh) - a start script to read the passed variables and produce the `config.js` file.
```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +# FAQ
```suggestion
## FAQ

```

2024-12-09 11:18 UTC, m-mohr commented on docs/docker.md
> +You can not. You need to build your own image because `pathPrefix` is a build only param.
```suggestion
You can not. You need to build your own image because `pathPrefix` is a build-only option.
```

2024-12-09 11:50 UTC, alekzvik commented
I agree with your suggestion to move out the docker section. 
I yanked it in full in this revision and left a small note with a link in README.
Other editorial changes are also fixed.

2024-12-10 00:39 UTC, m-mohr commented on docs/docker.md
> +## How it works
```suggestion
## How it works

```

2024-12-10 00:39 UTC, m-mohr commented on docs/docker.md
> +## Essential parts
```suggestion
## Essential parts

```

2024-12-10 00:39 UTC, m-mohr commented on docs/docker.md
> +## FAQ
```suggestion
## FAQ

```

2024-12-10 00:40 UTC, m-mohr approved these changes
Thank you very much!

2024-12-10 00:40 UTC, merged

2024-12-10 12:43 UTC, alekzvik commented
@m-mohr Thank you for all the corrections and editing.